---
title: "Midterm"
author: "Yuki Joyama"
output: 
  pdf_document:
    latex_engine: xelatex
    extra_dependencies: ["fontspec", "amsmath", "amssymb", "unicode-math"]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, message = F, warning = F)

# libraries
library(tidyverse)
library(ggplot2)

# setup plot theme
theme_set(
  theme_bw() +
    theme(legend.position = "top")
  )
```

# Question 1
(1) We know all the potential outcomes, so the causal effect of the treatment for an individual can be calculated by $Y_1-Y_0$ ($Y_1$: the potential outcome of a disease if an individual is assigned new treatment, $Y_0$: the potential outcome of a disease if an individual is assigned standard treatment). The average causal effect is $E[Y_1-Y_0]=$ `r 6/20`. On average, the new treatment prevents disease in 30% more individuals compared to the standard treatment.

(2) Under consistency, SUTVA, randomizeation and positivity assumption, $ACE=E[Y_1 - Y_0] = E[Y_1 \mid A = 1] - E[Y_0 \mid A = 0]=E[Y \mid A = 1] - E[Y \mid A = 0]$  
Given the table, $E[Y \mid A = 1]=\frac{1+0+1+0+0+0+0+1+1+0}{10}=0.4$ and $E[Y \mid A = 0]=\frac{0+0+1+0+0+0+0+1+0+0}{10}=0.2$. So $ACE=0.4-0.2=0.2$.   
This suggest that the new treatment has 20% higher likelihood of disease prevention compared to standard treatment. 

(3) The observed effect in (2) is smaller than in (1). The counterfactuals in (2) are unknown, and knowing (1), it appears that some individuals who would have shown a preventive effect with the new treatment were assigned to the standard treatment group in (2). This potentially attenuates the effect observed in (2).

(4) 
(a) Observational study   
In an observational study, the intervention is not assigned randomly and the exposure is likely to be influenced by various factors. Moreover, we may observe different number of individuals in each exposure groups by the nature of the data collection process. This can leads to a biased estimates of the outcome effect.  

(b) Randomized controlled trial  
In RCT, the randomization of treatment (intervention) assignment leads to expected balance on both observed and unobserved covariates in each group. This can minimize confounding and allows for an unbiased estimate of treatment effect under the necessary assumptions. 


